#!/bin/bash
#
# Research Node Initializer
# Copyright (C) 2014-2015 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


tryToLoadModules()
{
   echo -en "Loading $1 modules: "
   pattern="$2"
   shift ; shift
   while [ $# -gt 0 ] ; do
      directory="$1"
      shift
      if [ -e "$directory" ] ; then
         modules="`find "$directory" -name "$pattern" | xargs --no-run-if-empty -n1 basename | sed -e "s/\.ko$//g" | sort`"
         for module in $modules ; do
            echo -en "$module "
            modprobe $module >/dev/null 2>&1
         done
      fi
   done
   echo ""
}


if [ "$1" == "start" ] ; then
   if [ -e /vservers ] ; then   # We are (probably) on a research node's root context
      kernel=`uname -r`
      tryToLoadModules "TCP"   "tcp_*.ko"   /lib/modules/${kernel}/kernel/net/ipv4/   /lib/modules/${kernel}/extra/net/ipv4/
      tryToLoadModules "MPTCP" "mptcp_*.ko" /lib/modules/${kernel}/kernel/net/mptcp/  /lib/modules/${kernel}/extra/net/mptcp/
      tryToLoadModules "SCTP"  "sctp*.ko"   /lib/modules/${kernel}/kernel/net/sctp/   /lib/modules/${kernel}/extra/net/sctp/
      tryToLoadModules "DCCP"  "dccp*.ko"   /lib/modules/${kernel}/kernel/net/dccp/   /lib/modules/${kernel}/extra/net/dccp/
      echo -en "Allowed TCP CCs: "
      availableCCs=`sysctl net.ipv4.tcp_available_congestion_control | sed -e "s/.*= //g"`
      sysctl -w net.ipv4.tcp_allowed_congestion_control="$availableCCs"
   fi

elif [ "$1" == "stop" ] ; then
   echo "STOP"

else
   echo >&2 "Usage: $0 start|stop"
fi
